# structures/data_models.py
"""
Data models for the structure-centric trading system.
"""

from __future__ import annotations
import hashlib
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any, Union
import pandas as pd
from datetime import datetime


def _mint_event_trade_id(
    symbol: str,
    timestamp: pd.Timestamp,
    structure_type: str,
    side: str,
) -> str:
    """Mint a deterministic trade_id from the detection's identity tuple
    (symbol, timestamp, structure_type, side). DETERMINISTIC is required:
    detect() is called multiple times per detection in the sub7 fast path
    (main_detector → bias inference → plan_*_strategy each invoke detect()),
    and all of them must produce the same id so detector_accepts.jsonl,
    DECISION, TRIGGER, ENTRY, and EXIT all join on a single key.

    Format mirrors diagnostics.diag_event_log.mint_trade_id (`SYMBOL_<8hex>`)
    so downstream code can't distinguish detection-time mints from any legacy
    runtime mints by string shape alone.

    Collision math: 2^32 namespace per (sym, ts, setup, side) — a single
    trading day has ~10^3 detections, so collision probability is ~10^-7.
    """
    key = f"{symbol}|{timestamp.isoformat() if hasattr(timestamp, 'isoformat') else str(timestamp)}|{structure_type}|{side}"
    h = hashlib.sha256(key.encode("utf-8")).hexdigest()[:8]
    return f"{symbol}_{h}"


@dataclass
class StructureEvent:
    """Represents a detected structure pattern in market data."""

    symbol: str
    timestamp: pd.Timestamp
    structure_type: str  # e.g., "orb_breakout", "vwap_reclaim", "support_bounce"
    side: str  # "long" or "short"
    confidence: float  # 0.0 to 1.0

    # Structure-specific data
    levels: Dict[str, float]  # e.g., {"entry": 100.0, "stop": 99.0, "target": 102.0}
    context: Dict[str, Any]   # Additional context data

    # Market conditions at detection
    price: float
    volume: Optional[float] = None
    indicators: Optional[Dict[str, float]] = None

    # Trade identity. Auto-minted at event creation so the same id flows from
    # detector_accepts.jsonl through DECISION → TRIGGER → ENTRY → EXIT. Detectors
    # may override by passing trade_id=... if they need deterministic ids in tests.
    trade_id: Optional[str] = None

    def __post_init__(self):
        if not self.trade_id:
            self.trade_id = _mint_event_trade_id(
                self.symbol, self.timestamp, self.structure_type, self.side,
            )


@dataclass
class MarketContext:
    """Market context for strategy planning."""

    symbol: str
    current_price: float
    timestamp: pd.Timestamp
    df_5m: pd.DataFrame
    session_date: datetime

    # Optional market data
    df_daily: Optional[pd.DataFrame] = None

    # Current session info
    orh: Optional[float] = None
    orl: Optional[float] = None

    # Previous day levels
    pdh: Optional[float] = None
    pdl: Optional[float] = None
    pdc: Optional[float] = None

    # Market regime
    regime: Optional[str] = None  # "trend", "chop", "squeeze"
    volatility: Optional[float] = None

    # Cap segment for cap-aware filters
    cap_segment: Optional[str] = None  # "large_cap", "mid_cap", "small_cap", "micro_cap"

    # Technical indicators
    indicators: Optional[Dict[str, float]] = None


@dataclass
class RiskParams:
    """Risk management parameters for a trade."""

    hard_sl: float  # Hard stop loss level
    risk_per_share: float  # Risk amount per share
    atr: Optional[float] = None  # ATR for context
    volatility_adj: Optional[float] = None  # Volatility adjustment factor

    # Position sizing
    max_position_size: Optional[int] = None
    risk_percentage: Optional[float] = None


@dataclass
class ExitLevels:
    """Exit levels and conditions for a trade."""

    # Target levels
    targets: List[Dict[str, Union[float, int]]]  # [{"level": 102.0, "qty_pct": 50, "rr": 2.0}]

    # Stop levels
    hard_sl: float
    trail_to: Optional[str] = None  # "breakeven", "t1", etc.

    # Exit conditions
    time_exit: Optional[str] = None  # Time-based exit
    structure_exit: Optional[Dict[str, Any]] = None  # Structure-based exit conditions

    # Overnight setups use scheduled exits (broker AMO at next-day open) instead
    # of price-triggered SL/T1/T2. When exit_mode is "scheduled_amo", the
    # executor IGNORES hard_sl/targets and instead places an AMO SELL at
    # scheduled_exit_at. Backward-compatible: default None preserves
    # existing intraday MIS behavior.
    exit_mode: Optional[str] = None      # 'scheduled_amo' for overnight setups; None = price-triggered
    scheduled_exit_at: Optional[pd.Timestamp] = None  # IST-naive; for scheduled_amo only


@dataclass
class TradePlan:
    """Complete trade plan generated by a structure."""

    # Basic trade info (required fields first)
    symbol: str
    side: str  # "long" or "short"
    structure_type: str
    entry_price: float
    risk_params: RiskParams
    exit_levels: ExitLevels
    qty: int
    notional: float
    confidence: float

    # Optional fields
    entry_zone: Optional[Dict[str, float]] = None  # {"min": 99.5, "max": 100.5}
    trade_id: Optional[str] = None
    timestamp: Optional[pd.Timestamp] = None
    market_context: Optional[MarketContext] = None
    notes: Optional[Dict[str, Any]] = None

    # Target re-anchor semantics consumed by services/target_recalc.py at fill
    # time. "structural" preserves target levels (price respects PDH/PDL/gap
    # edge, not arithmetic distance from entry); "r_multiple" recomputes
    # T1/T2 from actual_entry using the planned R multiples; "or_range"
    # recomputes ORB-style from the opening range. Default is "structural"
    # — the safe choice when a detector forgets to set it (preserves edge
    # rather than re-anchoring around a possibly-bad fill).
    target_anchor_type: str = "structural"


@dataclass
class StructureAnalysis:
    """Analysis result from a structure detector."""

    structure_detected: bool
    events: List[StructureEvent]
    quality_score: float  # 0-100

    # Analysis details
    analysis_notes: Optional[Dict[str, Any]] = None
    rejection_reason: Optional[str] = None