"""Build detector inventory by scanning structures/ and pipeline configs.

Outputs docs/edge_discovery/audit/00-detector-inventory.md mapping each
detector class to the setup types it emits.

Usage:
    python tools/edge_discovery/audit/build_inventory.py
"""
from __future__ import annotations
import json
from pathlib import Path
import re
from typing import Dict, List

REPO = Path(__file__).resolve().parents[3]
STRUCTURES = REPO / "structures"
CONFIGS = REPO / "config" / "pipelines"
OUTPUT = REPO / "docs" / "edge_discovery" / "audit" / "00-detector-inventory.md"


def find_detector_classes() -> Dict[str, str]:
    """Return {ClassName: file_path} for every BaseStructure subclass."""
    detectors = {}
    for f in sorted(STRUCTURES.glob("*_structure.py")):
        text = f.read_text(encoding="utf-8")
        for m in re.finditer(r"^class (\w+)\(BaseStructure\)", text, re.M):
            detectors[m.group(1)] = str(f.relative_to(REPO))
    return detectors


def find_setup_types_in_configs() -> Dict[str, List[str]]:
    """Return {config_file: [setup_types_listed]}."""
    configs = {}
    for f in sorted(CONFIGS.glob("*_config.json")):
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        setups = data.get("setup_types", [])
        if setups:
            configs[str(f.relative_to(REPO))] = setups
    return configs


def main():
    detectors = find_detector_classes()
    configs = find_setup_types_in_configs()

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8") as out:
        out.write("# Detector Inventory (auto-generated)\n\n")
        out.write(f"Generated by: `tools/edge_discovery/audit/build_inventory.py`\n\n")
        out.write(f"## Detector classes found: {len(detectors)}\n\n")
        out.write("| Class | File |\n|-------|------|\n")
        for cls, path in detectors.items():
            out.write(f"| `{cls}` | `{path}` |\n")
        out.write("\n## Setup types per pipeline config\n\n")
        for path, setups in configs.items():
            out.write(f"### `{path}` ({len(setups)} setups)\n")
            for s in setups:
                out.write(f"- `{s}`\n")
            out.write("\n")
        out.write("\n## Notes\n\n")
        out.write("Some detector classes (e.g. `ICTStructure`) emit MULTIPLE setup types.\n")
        out.write("The audit unit is the **detector class** (one audit doc per class), not\n")
        out.write("per-setup-type. When auditing, list all setup types the class emits in the\n")
        out.write("audit doc header.\n")

    print(f"Wrote {OUTPUT}")
    print(f"  {len(detectors)} detector classes")
    print(f"  {len(configs)} pipeline configs")


if __name__ == "__main__":
    main()
