"""ONE-SHOT: universe re-cut (Rs-turnover ceiling + continuous-history gate) on the FRESH POOL.

Pre-registered brief: specs/2026-07-29-brief-universe-recut-turnover-liquidity-history.md
(committed 550071f BEFORE this script ran; §3/§4/§5/§6/§7 are BINDING).

  Universe A = each setup's CURRENT production/sanity universe, unchanged.
  Universe B = A n {causal ADV20 turnover <= Rs 5,00,00,000/day}
                 n {>= 18 months continuous daily bars ending at the signal date}

  Window    = signals 2026-05-01 .. 2026-07-24 (fresh pool; never evaluated).

SEQUENCING (brief §6, enforced structurally below): fire counts are computed and the
power gate is applied BEFORE any outcome statistic exists. If pooled Universe-B fires
< 50 the script exits before `compute_outcomes()` is ever called — no PnL, expectancy
or PF is produced anywhere.

MECHANISM REPLICATION (brief §4): each setup is generated by its OWN already-validated
research harness, imported and driven over the fresh-pool window. No detector is
re-implemented here and no threshold is changed. Setups whose harness cannot address
the fresh pool are EXCLUDED and reported as gaps (never approximated).

Outputs (uncommitted): reports/sub9_sanity/_universe_recut_freshpool.csv
                       one line appended to docs/experiment_ledger.jsonl
"""
from __future__ import annotations

import json
import sys
from datetime import date, datetime
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tools" / "sub9_research"))

pd.set_option("display.width", 220)
pd.set_option("display.max_columns", 40)

CLEAN_DAILY = ROOT / "cache" / "preaggregate" / "clean_daily_from5m.feather"
OUT_CSV = ROOT / "reports" / "sub9_sanity" / "_universe_recut_freshpool.csv"
LEDGER = ROOT / "docs" / "experiment_ledger.jsonl"

# ---------------------------------------------------------------- locked parameters (brief §3/§5/§6)
FRESH_START = date(2026, 5, 1)
FRESH_END = date(2026, 7, 24)          # last session in clean_daily / the 2026_07 5m feather
TURNOVER_CEILING_INR = 5e7             # Rs 5,00,00,000 / day
HIST_MONTHS = 18
HIST_COVERAGE = 0.90                   # "continuous" := >= 90% of the master calendar's
                                       # sessions in the 18 months strictly before the signal date
POWER_GATE_MIN_POOLED_B = 50           # brief §6
MIN_N_FOR_DECISION = 15                # brief §6 — setups below this are reported, not decided on
ADOPT_MIN_PF_B = 1.10                  # brief §7
NO_CHANGE_BAND = 0.10                  # brief §7 — +/-10% of A on pooled expectancy

# Factor clustering (2026-07-27 factor-concentration study). The four multiday
# capitulation ledgers are ONE factor and count ONCE in the majority test.
CLUSTER = {
    "close_dn_overnight_long": "close_dn_overnight",
    "below_vwap_volume_revert_long": "below_vwap_long",
    "or_window_failure_fade_short": "short_open_fade",
    "mtf_capitulation_revert_long": "capitulation_multiday",
    "low52_capitulation_revert_long": "capitulation_multiday",
    "zscore_oversold_revert_long": "capitulation_multiday",
    "crash2d_revert_long": "capitulation_multiday",
}


def _bare(s) -> str:
    s = str(s).strip().upper()
    return s.split(":", 1)[1] if ":" in s else s


# ================================================================= Universe B gate
def build_universe_b_gate() -> Tuple[pd.DataFrame, dict]:
    """(symbol, date) -> adv20_turnover, hist_ok, univ_b_ok  over the fresh pool.

    ADV20 turnover uses the identical causal formula as the originating diagnostic
    (tools/sub9_research/diag_universe_expectancy_by_era.build_adv_panel):
        turnover = close * volume ; rolling(20, min_periods=15).mean().shift(1)

    History gate: for signal date D let T(D) be the master-calendar sessions t with
    D - 18 months <= t < D. A symbol passes iff it has bars on >= 90% of T(D).
    The master calendar is every distinct session in clean_daily_from5m.feather, so
    the gate measures presence in the SAME archive the backtests replay.
    """
    d = pd.read_feather(CLEAN_DAILY)
    d["symbol"] = d["symbol"].map(_bare)
    d["date"] = pd.to_datetime(d["date"])
    d = d.sort_values(["symbol", "date"]).reset_index(drop=True)

    d["turnover"] = d["volume"] * d["close"]
    g = d.groupby("symbol", sort=False)
    d["adv20_turnover"] = (
        g["turnover"].transform(lambda s: s.rolling(20, min_periods=15).mean())
        .groupby(d["symbol"]).shift(1)
    )

    cal = pd.DatetimeIndex(sorted(d["date"].unique()))
    cal_pos = {t: i for i, t in enumerate(cal)}
    syms = sorted(d["symbol"].unique())
    spos = {s: i for i, s in enumerate(syms)}

    pres = np.zeros((len(syms), len(cal)), dtype=np.int32)
    pres[d["symbol"].map(spos).values, d["date"].map(cal_pos).values] = 1
    cum = np.cumsum(pres, axis=1)
    cum_pad = np.hstack([np.zeros((len(syms), 1), dtype=cum.dtype), cum])  # [:, i] = through i-1

    start_idx = np.searchsorted(cal.values, (cal - pd.DateOffset(months=HIST_MONTHS)).values, "left")
    expected = np.arange(len(cal)) - start_idx
    counts = cum_pad[:, np.arange(len(cal))] - cum_pad[:, start_idx]
    hist_ok = (expected[None, :] > 0) & (counts >= HIST_COVERAGE * expected[None, :])

    fpos = np.where((cal >= pd.Timestamp(FRESH_START)) & (cal <= pd.Timestamp(FRESH_END)))[0]
    gate = pd.DataFrame(hist_ok[:, fpos], index=syms, columns=cal[fpos]).stack().rename("hist_ok")
    gate = gate.reset_index()
    gate.columns = ["symbol", "date", "hist_ok"]
    gate = gate.merge(d[["symbol", "date", "adv20_turnover"]], on=["symbol", "date"], how="left")
    # A symbol-day with no live causal ADV20 cannot be VERIFIED under the ceiling ->
    # it fails Universe B. Conservative and stated up front.
    gate["turnover_ok"] = gate["adv20_turnover"].notna() & (gate["adv20_turnover"] <= TURNOVER_CEILING_INR)
    gate["univ_b_ok"] = gate["turnover_ok"] & gate["hist_ok"]

    meta = {
        "panel_symbols": len(syms),
        "master_calendar_sessions": len(cal),
        "fresh_sessions": len(fpos),
        "expected_sessions_in_18m_lookback": [int(expected[fpos].min()), int(expected[fpos].max())],
        "symbols_passing_history_gate_mean": float(hist_ok[:, fpos].sum(0).mean()),
        "fresh_symbol_days": int(len(gate)),
        "share_turnover_ok": float(gate["turnover_ok"].mean()),
        "share_hist_ok": float(gate["hist_ok"].mean()),
        "share_univ_b_ok": float(gate["univ_b_ok"].mean()),
    }
    return gate, meta


# ================================================================= per-setup fresh-pool generators
def gen_close_dn_overnight_long() -> pd.DataFrame:
    """MACHINERY: tools/sub9_research/sanity_close_dn_overnight_5bar.run_window
    (the 5-bar realistic-live signal the LIVE cell #5 lock is measured on), with the
    cell #5 filter from tools/sub9_research/close_dn_overnight_long_cell_lock.json
    applied exactly as diag_universe_expectancy_by_era.load_ledger does.
    COST MODEL: calc_fee_cnc (sanity_close_dn_overnight_long) — CNC delivery.
    NOTIONAL: entry_price * qty (POSITION_NOTIONAL_INR = Rs 1,00,000).
    """
    import tools.sub9_research.sanity_close_dn_overnight_5bar as m
    m.WINDOWS["fresh"] = (FRESH_START, FRESH_END)      # shared dict with the parent module
    t = m.run_window("fresh")
    if t.empty:
        return t
    t = t[(t["closing_30m_volume_z_bin"] == "extreme")
          & (t["prior_day_return_bin"] == "up_gt_3pct")].copy()
    t["notional_inr"] = t["entry_price"].astype(float) * t["qty"].astype(float)
    return t[["signal_date", "symbol", "net_pnl_inr", "notional_inr"]]


_BV_CACHE = ROOT / "reports" / "sub9_sanity" / "_below_vwap_freshpool_raw_sanity.csv"


def gen_below_vwap_volume_revert_long() -> pd.DataFrame:
    """MACHINERY: tools/sub9_research/sanity_below_vwap_volume_revert_long.run_window
    for the raw signal population, THEN the SHIPPED cell lock from
    tools/sub9_research/below_vwap_volume_revert_long_cell_lock.json applied on top:
      * 3D cell_filter  cap_segment=unknown x vol_ratio_bin=gte_10 x hhmm_bucket=afternoon_1300_1500
      * locked exit grid t1=1.5R / t2=2.0R / sl=1.0R / ts=14:30 / partial_50_no_trail,
        re-simulated with tools/methodology/cell_sweep._row_simulate (the same resim
        tools/sub9_research/apply_lock_below_vwap_oos_ho.py uses to apply this lock).
    The raw sanity population is NOT the mechanism we run — it is ~100x the production
    fire rate — so scoring it would be an unfaithful replication.

    run_window's _load_window has no lookback pad and vol_ratio needs rolling(20,
    min_periods=20) per (symbol, hhmm), so the harness is driven over
    2026-03-02..2026-07-24 and the output is then restricted to fresh-pool signal
    dates. That gives fresh-pool signals the same fully-warm baseline a mid-window
    signal gets in the original windows; no threshold or rule is altered.

    COST MODEL: calc_fee (MIS intraday, tools/sub7_validation/build_per_setup_pnl).
    NOTIONAL: entry_price * qty (Rs 1,000 risk-based sizing).
    """
    import json as _json
    from tools.methodology.cell_sweep import CellSweepConfig, GridEntry, _row_simulate
    from tools.sub7_validation.build_per_setup_pnl import calc_fee

    if _BV_CACHE.exists():
        t = pd.read_csv(_BV_CACHE)
        print(f"     (reusing cached raw sanity population {_BV_CACHE.name}: {len(t)} rows)")
    else:
        import tools.sub9_research.sanity_below_vwap_volume_revert_long as m
        m.WINDOWS["fresh"] = (date(2026, 3, 2), FRESH_END)
        t = m.run_window("fresh")
        if t is None or t.empty:
            return pd.DataFrame()
        _BV_CACHE.parent.mkdir(parents=True, exist_ok=True)
        t.to_csv(_BV_CACHE, index=False)

    t["signal_date"] = pd.to_datetime(t["signal_date"])
    t = t[(t["signal_date"] >= pd.Timestamp(FRESH_START))
          & (t["signal_date"] <= pd.Timestamp(FRESH_END))].copy()
    n_raw = len(t)

    lock = _json.loads(
        (ROOT / "tools" / "sub9_research" / "below_vwap_volume_revert_long_cell_lock.json")
        .read_text(encoding="utf-8"))
    cf = {k: v for k, v in lock["cell_filter"].items() if not k.startswith("comment")}
    for k, v in cf.items():
        t = t[t[k] == v]
    n_cell = len(t)

    gspec = lock["grid"]
    grid = GridEntry(label=gspec["label"], ts_hhmm=int(gspec["ts_hhmm"]),
                     partial_mode=gspec["partial_mode"], t1=float(gspec["t1_R"]),
                     t2=float(gspec["t2_R"]), sl=float(gspec["sl_R"]))
    cfg = CellSweepConfig(side="LONG", target_unit="R", grid=[grid],
                          dim_pool=list(cf.keys()))
    close_col = f"close_at_{int(gspec['ts_hhmm'])}"
    t = t.dropna(subset=[close_col, "mfe_r", "mae_r", "R_per_share"])
    nets = [_row_simulate(r, cfg, grid, close_col, calc_fee) for _, r in t.iterrows()]
    t = t.assign(net_pnl_inr=nets).dropna(subset=["net_pnl_inr"])
    print(f"     cell lock: raw fresh-pool signals {n_raw} -> 3D cell {n_cell} -> "
          f"locked-grid resim {len(t)}")
    t["notional_inr"] = t["entry_price"].astype(float) * t["qty"].astype(float)
    return t[["signal_date", "symbol", "net_pnl_inr", "notional_inr"]]


def gen_or_window_failure_fade_short() -> pd.DataFrame:
    """MACHINERY: tools/sub9_research/sanity_or_window_failure_fade — its own
    _load_5m_for_month / _cap_segment / _is_mis_eligible / _simulate_day driven over
    the fresh-pool months. This reproduces main()'s trade-generation loop verbatim
    (main() itself only adds printing and CSV writing).
    COST MODEL: calc_fee (MIS intraday) inside _path_walk.
    NOTIONAL: entry_price * qty (Rs 1,000 risk-based sizing).
    """
    import tools.sub9_research.sanity_or_window_failure_fade as m
    m.WINDOW_START, m.WINDOW_END, m.WINDOW_LABEL = FRESH_START, FRESH_END, "fresh"
    rows: List[dict] = []
    for (y, mm) in m._months_in_window():
        mdf = m._load_5m_for_month(y, mm)
        if mdf.empty:
            continue
        mdf["d"] = mdf["date"].dt.date
        mdf = mdf[(mdf["d"] >= m.WINDOW_START) & (mdf["d"] <= m.WINDOW_END)]
        if mdf.empty:
            continue
        syms = set(mdf["symbol"].unique())
        cap = {s: m._cap_segment(s) for s in syms}
        mis = {s: m._is_mis_eligible(s) for s in syms}
        keep = {s for s in syms if cap.get(s) in m.ALLOWED_CAPS and mis.get(s)}
        mdf = mdf[mdf["symbol"].isin(keep)]
        if mdf.empty:
            continue
        print(f"    or_window {y:04d}-{mm:02d}: {mdf['symbol'].nunique()} symbols, {mdf['d'].nunique()} days", flush=True)
        for (sym, dd), grp in mdf.groupby(["symbol", "d"], sort=False):
            tr = m._simulate_day(sym, grp.sort_values("date").reset_index(drop=True), cap.get(sym, "unknown"))
            if tr is not None:
                rows.append(tr)
        del mdf
    if not rows:
        return pd.DataFrame()
    t = pd.DataFrame(rows)
    t = t.rename(columns={"trade_date": "signal_date", "net_pnl": "net_pnl_inr"})
    t["notional_inr"] = t["entry_price"].astype(float) * t["qty"].astype(float)
    return t[["signal_date", "symbol", "net_pnl_inr", "notional_inr"]]


def gen_multiday_capitulation() -> Dict[str, pd.DataFrame]:
    """MACHINERY: tools/sub9_research/multiday_target_exit_study.build_trades (the
    exact selection used by monster_conditioning_validation to produce the BASELINE
    ledgers the diagnostic read) + its baseline hold-to-close geometry.
    COST MODEL: calc_fee_mtf at Rs 1,00,000 margin x 2.79 leverage.
    NOTIONAL: MARGIN * LEV = Rs 2,79,000 (constant, as in the baseline ledger).
    Runs entirely on clean_daily_from5m.feather, which covers the fresh pool.
    """
    from multiday_target_exit_study import CLEAN, CELLS, MARGIN, LEV, load_eligible, build_trades
    from monster_conditioning_validation import net_pnl_row

    dd = pd.read_feather(CLEAN)
    dd["date"] = pd.to_datetime(dd["date"])
    dd["bare"] = dd["symbol"].astype(str).str.replace("NSE:", "", regex=False).str.upper()
    elig = load_eligible()

    out: Dict[str, pd.DataFrame] = {}
    for name, (mode, params) in CELLS.items():
        sel, K = build_trades(dd, elig, mode, params)
        sel = sel[(sel["date"] >= pd.Timestamp(FRESH_START)) & (sel["date"] <= pd.Timestamp(FRESH_END))].copy()
        if sel.empty:
            out[name] = pd.DataFrame()
            continue
        sel["net_pnl_inr"] = [net_pnl_row(e, x, K + 1)
                              for e, x in zip(sel["open_next"].values, sel["close_exit"].values)]
        sel["signal_date"] = pd.to_datetime(sel["date"])
        sel["notional_inr"] = MARGIN * LEV
        out[name] = sel[["signal_date", "symbol", "net_pnl_inr", "notional_inr"]].reset_index(drop=True)
        print(f"    {name}: {len(out[name])} fresh-pool fires (K={K})", flush=True)
    return out


# setups in brief §4 that CANNOT be faithfully replicated on the fresh pool.
EXCLUSIONS = {
    "panic_crash_revert_long": (
        "No standalone offline harness exists. Its only per-trade source is the OCI "
        "full-backtest production pipeline (reports/oci_canonical/*.csv via "
        "tools/methodology/aggregate_oci_to_canonical.py over a main.py --dry-run run "
        "directory), which has not been run past 2026-04-30. Re-implementing the "
        "detector offline would be an approximation, not a replication."
    ),
    "up_spike_fade_short": (
        "Same as panic_crash_revert_long — OCI production pipeline is the only trade "
        "source; no offline sanity/sweep harness in tools/."
    ),
    "long_panic_gap_down": (
        "tools/sub9_research/sanity_long_panic_gap_down.py sources prior-day high/low/"
        "close from cache/preaggregate/consolidated_daily.feather, which ends 2026-04-30 "
        "(it silently yields 0 trades past that date). Repointing it to "
        "clean_daily_from5m.feather would change the daily inputs that DEFINE the signal "
        "(unadjusted+bad-print vs CA-adjusted), so the fresh-pool signals would not be "
        "the same mechanism the ledger measured."
    ),
}


# ================================================================= statistics (brief §7)
def _pf(x: np.ndarray) -> float:
    w, l = x[x > 0].sum(), -x[x < 0].sum()
    return float(w / l) if l > 0 else (np.inf if w > 0 else np.nan)


def _stats(df: pd.DataFrame) -> dict:
    if df.empty:
        return {"n": 0, "exp_bps": np.nan, "net_pf": np.nan, "wr_pct": np.nan, "net_inr": 0.0}
    net = df["net_pnl_inr"].values
    return {
        "n": int(len(df)),
        "exp_bps": float(df["net_bps"].mean()),
        "net_pf": _pf(net),
        "wr_pct": float((net > 0).mean() * 100),
        "net_inr": float(net.sum()),
    }


def compute_outcomes(trades: pd.DataFrame) -> Tuple[pd.DataFrame, dict, str, List[str]]:
    """Called ONLY after the power gate passes (brief §6)."""
    trades = trades.copy()
    trades["net_bps"] = trades["net_pnl_inr"] / trades["notional_inr"] * 10_000.0

    rows = []
    for setup, g in trades.groupby("setup"):
        for uni, sub in (("A", g), ("B", g[g["univ_b_ok"]])):
            r = {"level": "setup", "unit": setup, "cluster": CLUSTER[setup], "universe": uni}
            r.update(_stats(sub))
            rows.append(r)
    for cl, g in trades.groupby("cluster"):
        for uni, sub in (("A", g), ("B", g[g["univ_b_ok"]])):
            r = {"level": "cluster", "unit": cl, "cluster": cl, "universe": uni}
            r.update(_stats(sub))
            rows.append(r)
    for uni, sub in (("A", trades), ("B", trades[trades["univ_b_ok"]])):
        r = {"level": "pooled", "unit": "ALL", "cluster": "ALL", "universe": uni}
        r.update(_stats(sub))
        rows.append(r)
    res = pd.DataFrame(rows)

    pa = res[(res.level == "pooled") & (res.universe == "A")].iloc[0]
    pb = res[(res.level == "pooled") & (res.universe == "B")].iloc[0]

    # majority test on DECISION UNITS = clusters (multiday capitulation counts ONCE),
    # restricted to units with n >= 15 in BOTH universes.
    units, notes = [], []
    for cl, g in res[res.level == "cluster"].groupby("unit"):
        a = g[g.universe == "A"].iloc[0]
        b = g[g.universe == "B"].iloc[0]
        eligible = (a["n"] >= MIN_N_FOR_DECISION) and (b["n"] >= MIN_N_FOR_DECISION)
        units.append({"unit": cl, "n_A": a["n"], "n_B": b["n"], "exp_bps_A": a["exp_bps"],
                      "exp_bps_B": b["exp_bps"], "eligible": eligible,
                      "B_better": bool(eligible and b["exp_bps"] > a["exp_bps"])})
    ut = pd.DataFrame(units)
    elig = ut[ut["eligible"]]
    majority = bool(len(elig) and elig["B_better"].sum() * 2 > len(elig))

    ea, eb = float(pa["exp_bps"]), float(pb["exp_bps"])
    rel = abs(eb - ea) / abs(ea) if ea != 0 else np.inf

    # Precedence FIXED before any number was seen: the +/-10% band is the more
    # specific rule and is evaluated first, so a noise-level shortfall reads as
    # NO CHANGE rather than REJECT (the band exists for exactly that purpose).
    if rel <= NO_CHANGE_BAND:
        verdict = "no_change"
        notes.append(f"pooled B within +/-{NO_CHANGE_BAND:.0%} of A ({rel:.1%}) -> NO CHANGE (§7)")
    elif eb > ea and float(pb["net_pf"]) >= ADOPT_MIN_PF_B and majority:
        verdict = "adopt"
        notes.append("B > A, B pooled net PF >= 1.10, and B better in a majority of eligible units")
    elif eb < ea:
        verdict = "reject"
        notes.append(f"pooled B expectancy < A by {rel:.1%} (outside the +/-10% band)")
    else:
        verdict = "no_change"
        notes.append(f"B > A by {rel:.1%} but PF_B={pb['net_pf']:.3f} (>=1.10? "
                     f"{float(pb['net_pf']) >= ADOPT_MIN_PF_B}) / majority={majority} -> NO CHANGE")

    summary = {
        "pooled_A": {k: (None if pd.isna(pa[k]) else float(pa[k])) for k in ("n", "exp_bps", "net_pf", "wr_pct", "net_inr")},
        "pooled_B": {k: (None if pd.isna(pb[k]) else float(pb[k])) for k in ("n", "exp_bps", "net_pf", "wr_pct", "net_inr")},
        "rel_change_exp": float(rel) if np.isfinite(rel) else None,
        "majority_units_eligible": int(len(elig)),
        "majority_units_B_better": int(elig["B_better"].sum()) if len(elig) else 0,
        "majority_test": majority,
    }
    return res, summary, verdict, notes, ut


# ================================================================= main
def main() -> int:
    print("=" * 112)
    print("ONE-SHOT — universe re-cut (Rs5cr ADV20 turnover ceiling + 18-month continuous history)")
    print(f"  brief: specs/2026-07-29-brief-universe-recut-turnover-liquidity-history.md  (PRE-REGISTERED)")
    print(f"  FRESH POOL: signals {FRESH_START} .. {FRESH_END}   ONE RUN, NO ITERATION")
    print("=" * 112)

    print("\n### STEP 1 — Universe-B gate panel")
    gate, meta = build_universe_b_gate()
    for k, v in meta.items():
        print(f"    {k}: {v}")
    print(f'    "continuous" := >= {HIST_COVERAGE:.0%} of the master-calendar sessions in the '
          f"{HIST_MONTHS} months strictly before the signal date")

    print("\n### STEP 2 — fresh-pool signal generation per setup (each setup's OWN harness)")
    frames: List[pd.DataFrame] = []

    gens = [
        ("close_dn_overnight_long", gen_close_dn_overnight_long),
        ("below_vwap_volume_revert_long", gen_below_vwap_volume_revert_long),
        ("or_window_failure_fade_short", gen_or_window_failure_fade_short),
    ]
    for name, fn in gens:
        print(f"\n  -- {name}")
        t = fn()
        if t is None or t.empty:
            print(f"     0 fresh-pool fires")
            continue
        t = t.copy()
        t["setup"] = name
        frames.append(t)
        print(f"     {len(t)} fresh-pool fires")

    print(f"\n  -- multiday capitulation cluster (ONE factor)")
    for name, t in gen_multiday_capitulation().items():
        if t is None or t.empty:
            continue
        t = t.copy()
        t["setup"] = name
        frames.append(t)

    print(f"\n  -- EXCLUDED (brief §4 members that cannot be faithfully replicated):")
    for name, why in EXCLUSIONS.items():
        print(f"     {name}: {why}")

    trades = pd.concat(frames, ignore_index=True)
    trades["signal_date"] = pd.to_datetime(trades["signal_date"])
    trades["sym"] = trades["symbol"].map(_bare)
    trades["cluster"] = trades["setup"].map(CLUSTER)

    trades = trades.merge(
        gate.rename(columns={"symbol": "sym", "date": "signal_date"}),
        on=["sym", "signal_date"], how="left",
    )
    for c in ("hist_ok", "turnover_ok", "univ_b_ok"):
        trades[c] = trades[c].fillna(False).astype(bool)

    # ---------------------------------------------------------- STEP 3: POWER GATE (before any outcome)
    print("\n" + "=" * 112)
    print("### STEP 3 — PRE-REGISTERED POWER GATE (brief §6) — evaluated BEFORE any outcome statistic")
    print("=" * 112)
    cnt = trades.groupby("setup").agg(
        fires_A=("univ_b_ok", "size"),
        fires_B=("univ_b_ok", "sum"),
        turnover_ok=("turnover_ok", "sum"),
        hist_ok=("hist_ok", "sum"),
    )
    cnt["cluster"] = [CLUSTER[s] for s in cnt.index]
    cnt["retention_B_pct"] = (cnt["fires_B"] / cnt["fires_A"] * 100).round(1)
    print("\n--- per setup ---")
    print(cnt[["cluster", "fires_A", "fires_B", "retention_B_pct", "turnover_ok", "hist_ok"]].to_string())

    ccnt = trades.groupby("cluster").agg(fires_A=("univ_b_ok", "size"), fires_B=("univ_b_ok", "sum"))
    ccnt["retention_B_pct"] = (ccnt["fires_B"] / ccnt["fires_A"] * 100).round(1)
    print("\n--- per factor cluster (decision units; multiday capitulation = ONE) ---")
    print(ccnt.to_string())

    pooled_a, pooled_b = int(len(trades)), int(trades["univ_b_ok"].sum())
    print(f"\n  POOLED fires   Universe A = {pooled_a}    Universe B = {pooled_b}")
    print(f"  GATE: pooled Universe-B fires >= {POWER_GATE_MIN_POOLED_B}? "
          f"{'PASS' if pooled_b >= POWER_GATE_MIN_POOLED_B else 'FAIL -> POWER-BLOCKED'}")

    counts_rows = []
    for s, r in cnt.iterrows():
        counts_rows.append({"level": "setup", "unit": s, "cluster": r["cluster"], "universe": "A",
                            "n": int(r["fires_A"]), "phase": "power_gate"})
        counts_rows.append({"level": "setup", "unit": s, "cluster": r["cluster"], "universe": "B",
                            "n": int(r["fires_B"]), "phase": "power_gate"})

    if pooled_b < POWER_GATE_MIN_POOLED_B:
        # ---- POWER-BLOCKED: report counts only, compute NOTHING else.
        per_month = trades[trades["univ_b_ok"]].groupby(
            trades["signal_date"].dt.to_period("M")).size()
        rate = pooled_b / max(1, trades["signal_date"].dt.to_period("M").nunique())
        need = int(np.ceil((POWER_GATE_MIN_POOLED_B - pooled_b) / max(rate, 1e-9)))
        proj = (pd.Period(FRESH_END, "M") + need).strftime("%Y-%m")
        print(f"\n  monthly Universe-B fire rate: {per_month.to_dict()}  (mean {rate:.1f}/month)")
        print(f"  PROJECTED month reaching {POWER_GATE_MIN_POOLED_B} pooled B fires: {proj}")
        print("\n  NO PnL / expectancy / PF computed anywhere (brief §6).")
        out = pd.DataFrame(counts_rows)
        out.to_csv(OUT_CSV, index=False)
        _append_ledger("power_blocked", {
            "pooled_fires_A": pooled_a, "pooled_fires_B": pooled_b,
            "power_gate_min": POWER_GATE_MIN_POOLED_B,
            "projected_month_reaching_gate": proj,
            "outcome_statistics_computed": False,
            "excluded_setups": sorted(EXCLUSIONS),
        }, notes=(
            f"POWER-BLOCKED per brief §6: pooled Universe-B fires = {pooled_b} < "
            f"{POWER_GATE_MIN_POOLED_B}. NO PnL / expectancy / PF computed anywhere. "
            f"Universe-A pooled fires = {pooled_a}. Projected month reaching the gate: {proj}. "
            f"Excluded (not faithfully replicable on the fresh pool): {', '.join(sorted(EXCLUSIONS))}. "
            "Ledger line is NOT a §7 verdict; the one-shot is rescheduled, not spent."
        ))
        print(f"\nWROTE {OUT_CSV}")
        return 0

    # ---------------------------------------------------------- STEP 4: outcomes
    print("\n" + "=" * 112)
    print("### STEP 4 — OUTCOMES (gate passed).  Primary = pooled net expectancy in bps of position notional")
    print("=" * 112)
    res, summary, verdict, notes, ut = compute_outcomes(trades)

    show = res.copy()
    for c in ("exp_bps", "net_pf", "wr_pct"):
        show[c] = show[c].astype(float).round(3)
    show["net_inr"] = show["net_inr"].round(0)
    print("\n--- per setup ---")
    print(show[show.level == "setup"].sort_values(["unit", "universe"]).to_string(index=False))
    print("\n--- per factor cluster (decision units) ---")
    print(show[show.level == "cluster"].sort_values(["unit", "universe"]).to_string(index=False))
    print("\n--- POOLED ---")
    print(show[show.level == "pooled"].to_string(index=False))

    print("\n--- majority test (units with n >= 15 in BOTH universes) ---")
    print(ut.round(2).to_string(index=False))
    print(f"    eligible units: {summary['majority_units_eligible']}   "
          f"B better in: {summary['majority_units_B_better']}   majority={summary['majority_test']}")

    print("\n" + "=" * 112)
    print(f"### §7 VERDICT (applied mechanically): {verdict.upper()}")
    for n in notes:
        print(f"    - {n}")
    print("=" * 112)

    out = pd.concat([pd.DataFrame(counts_rows), res.assign(phase="outcome")], ignore_index=True)
    out.to_csv(OUT_CSV, index=False)
    print(f"\nWROTE {OUT_CSV}  ({len(out)} rows)")

    _append_ledger(verdict, {
        "pooled_fires_A": pooled_a, "pooled_fires_B": pooled_b,
        "power_gate_min": POWER_GATE_MIN_POOLED_B, "power_gate": "pass",
        **summary,
        "decision_notes": notes,
        "excluded_setups": sorted(EXCLUSIONS),
        "flag_8_2_decomposition_required": verdict == "adopt",
    }, notes=(
        f"§7 verdict {verdict.upper()} applied mechanically. Pooled net expectancy (bps of "
        f"position notional): A={summary['pooled_A']['exp_bps']:.1f} (n={pooled_a}) vs "
        f"B={summary['pooled_B']['exp_bps']:.1f} (n={pooled_b}); pooled net PF "
        f"A={summary['pooled_A']['net_pf']:.3f} vs B={summary['pooled_B']['net_pf']:.3f}. "
        f"Majority test on factor-cluster decision units (multiday capitulation counts ONCE, "
        f"units need n>=15 in both universes): B better in "
        f"{summary['majority_units_B_better']}/{summary['majority_units_eligible']} -> "
        f"{summary['majority_test']}. " + " | ".join(notes) +
        f" Excluded (not faithfully replicable on the fresh pool): "
        f"{', '.join(sorted(EXCLUSIONS))}."
    ))
    return 0


def _append_ledger(verdict: str, payload: dict, notes: str = "") -> None:
    line = {
        "date": datetime.now().strftime("%Y-%m-%d"),
        "setup": "_universe_recut_turnover_ceiling_plus_history_gate",
        "variant": (
            "Universe B = each setup's CURRENT production universe (A) n {causal ADV20 "
            "turnover <= Rs5,00,00,000/day; close*volume, rolling(20,min_periods=15)"
            ".mean().shift(1)} n {>= 18 months continuous daily bars ending at the signal "
            f"date, 'continuous' := >= {HIST_COVERAGE:.0%} of master-calendar sessions, "
            "clean_daily_from5m.feather}. Same mechanisms / signals / exits / cost models "
            "under both universes; only symbol eligibility differs. Each setup generated by "
            "its OWN validated harness over the fresh pool."
        ),
        "stage": "universe_recut_oneshot",
        "windows": ["post_freeze:2026-05-01"],
        "verdict": verdict,
        "evidence": "reports/sub9_sanity/_universe_recut_freshpool.csv + "
                    "tools/sub9_research/oneshot_universe_recut_freshpool.py",
        "notes": notes,
        "brief": "specs/2026-07-29-brief-universe-recut-turnover-liquidity-history.md",
        "fresh_pool": f"{FRESH_START}..{FRESH_END}",
        **payload,
    }
    LEDGER.parent.mkdir(parents=True, exist_ok=True)
    with LEDGER.open("a", encoding="utf-8") as f:
        f.write(json.dumps(line, default=str) + "\n")
    print(f"APPENDED ledger line -> {LEDGER}  (verdict={verdict})")


if __name__ == "__main__":
    raise SystemExit(main())
